In [61]:
import os
import pickle
import numpy as np

pa_pickle = "/home/deepvisionpoc/Desktop/Jeans/SOLIDER_exp/SOLIDER-PersonAttributeRecognition/data/PA100k/dataset_all.pkl"

with open(pa_pickle, 'rb') as f:
    data = pickle.load(f)
    
print(data.keys())

train_label = data.label[0:80000]
class_count = np.sum(train_label, axis=0)
total_sample = train_label.shape[0]
print(len(class_count))
# Calculate the class weights
class_weights = total_sample / (len(class_count) * class_count)
# print(class_weights)
# print("description", data.description,'\n')
# print("reorder", data.reorder,'\n')
# print("root", data.root,'\n')
# print("image_name", type(data.image_name),'\n')
print("label", data.label,'\n')
# print("attr_name", data.attr_name,'\n')
# print("label_idx", len(data.label_idx.eval),'\n')
print("partition", data.partition,'\n')
print("weight_train", data.weight_train, '\n')
# print("weight_trainval", data.weight_trainval,'\n')


dict_keys(['description', 'reorder', 'root', 'image_name', 'label', 'attr_name', 'label_idx', 'partition', 'weight_train', 'weight_trainval'])
26
label [[1 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]] 

partition {'train': array([    0,     1,     2, ..., 79997, 79998, 79999]), 'val': array([80000, 80001, 80002, ..., 89997, 89998, 89999]), 'test': array([90000, 90001, 90002, ..., 99997, 99998, 99999]), 'trainval': array([    0,     1,     2, ..., 89997, 89998, 89999])} 

weight_train [0.45615   0.0140875 0.9340125 0.0519    0.358975  0.283825  0.3572
 0.04395   0.1791375 0.1835    0.191125  0.1475875 0.0096375 0.585975
 0.414025  0.0509625 0.1540375 0.108625  0.044     0.00505   0.0177625
 0.0282    0.7089875 0.173875  0.1171375 0.0061875] 

